name: env_axplorer
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.10,<3.14
  - numpy
  - numba
  - tqdm
  - pyyaml
  - psutil
  - pytorch-cuda=12.4
  - pytorch::pytorch
  - pip
